### PR TITLE
Remove the compiled directory from git

### PR DESCRIPTION
**Pull request by rjcorwin**
`src/compiled*` is in the `.gitignore` but there were items in this folder that were in git. I think this branch cleans that up. Nice for a clean `git status` when working.

### CODE REVIEW

**Comment by rjcorwin** [comment]
Looks like this breaks some things. This is my screen after running `npm start` fresh.
screen shot 2015-12-16 at 10 10 24 am

**Comment by chrisekelley** [comment]
Yeah, we need the compiled directory for the index-dev.html/npm run debug version. I recommend we it in there.

**Comment by chrisekelley** [comment]
Once sourcemaps debugging is working in Chrome again, we can remove this whole work-around.

**Comment by chrisekelley** [comment]
Man Slack is fast!

;-)

**Pull request closed without merging**
